Vladimir Popov Task 15
eugene-okulik/Vladimir_Popov pull request #15
Opened 2024-02-04 19:50 UTC by Wladdima

Евгений, по задаче возникли вопросы:

1) Если мы добавляем сразу несколько записей в базу через один запрос, то как можно потом с помощью методов cursor получить сразу несколько id всех элементов, которые мы добавлили в одном запросе. Через какой-нибудь цикл с cursor.lastrowid?
2) У меня получилось вывести информацию о студенте, но почему-то выводится только имя, фамилия, и lesson. Но почему-то не выводится информация об оценках, предметах и книгах. Я не знаю почему, запрос с join использовал тот же. В базе данных он работает. 

Подскажи, пожалуйста, в чем может быть ошибка. Я ее найти не смог

2024-02-05 11:58 UTC, eugene-okulik commented
> Евгений, по задаче возникли вопросы:
> 
> 1. Если мы добавляем сразу несколько записей в базу через один запрос, то как можно потом с помощью методов cursor получить сразу несколько id всех элементов, которые мы добавлили в одном запросе. Через какой-нибудь цикл с cursor.lastrowid?
> 2. У меня получилось вывести информацию о студенте, но почему-то выводится только имя, фамилия, и lesson. Но почему-то не выводится информация об оценках, предметах и книгах. Я не знаю почему, запрос с join использовал тот же. В базе данных он работает.
> 
> Подскажи, пожалуйста, в чем может быть ошибка. Я ее найти не смог

1. Никак. Если нам для каждой добавленной записи нужно получить `Id`, то нужно делать это единичными инсертами и сохранять айди сразу после инсерта
2. Ща посмотрю

2024-02-05 12:12 UTC, eugene-okulik requested changes
Из того, что необходимо поправить - чтобы выводились все необходимые данные.

2024-02-05 12:12 UTC, eugene-okulik commented on homework/vladimir_popov/Task15/Part1.py
> +                         "VALUES (%s, %s, %s)"
Перенос с помощью `\` не рекомендуется. Правильнее так:
```python
insert_new_group_query = (
    "INSERT INTO `groups` (title, start_date, end_date) "
    "VALUES (%s, %s, %s)"
)
```

2024-02-05 12:12 UTC, eugene-okulik commented on homework/vladimir_popov/Task15/Part1.py
> +WHERE s.id = {student_id}
Здесь ты таки не удержался и использовал питоновскую подстановку, а не `%s`. Если делаешь что-то для себя или на своем проекте, то нормально. Тем более что этот student_id у нас здесь же и генерится. Но если будешь что-то такое делать на собесе или в тестовом, то лучше везде пользоваться `%s`

2024-02-05 12:12 UTC, eugene-okulik commented on homework/vladimir_popov/Task15/Part1.py
> +all_info_query = f'''SELECT s.name, s.second_name, g.title, b.title, s2.title , l.title, m.value
По поводу твоего второго вопроса. Ты здесь достаешь из разных таблиц колонки с одинаковыми названиями. И базе данных это норм - она как-то это показывает. Но каждая колонка называется просто title. Но здесь же мы всё преобразуем в словарь, а в словаре все ключи уникальны. Вот данные и теряются. Решается это с помощью
```python
all_info_query = f'''SELECT s.name, s.second_name, g.title as group_title, b.title as book_title, s2.title as subj_title , l.title as lesson_title, m.value
```

2024-02-10 22:07 UTC, Wladdima commented
Исправил, информация о студенте теперь отображается нормально

2024-02-11 07:52 UTC, eugene-okulik approved these changes

2024-02-11 07:52 UTC, merged