Vladimir Popov Task 16
eugene-okulik/Vladimir_Popov pull request #16
Opened 2024-02-11 20:05 UTC by Wladdima

2024-02-12 10:35 UTC, eugene-okulik requested changes

2024-02-12 10:35 UTC, eugene-okulik commented on homework/vladimir_popov/Task16/Part1.py
> +        if not student_id:
Ты делаешь проверку только на существование такого студента в базе данных. Но нужно проверять существует ли в базе вся строка. Даже если есть такой студент, но у него нет такой оценки как указано в файле, значит таких данных нет в базе. То есть, нужно проверить всю строку.
Можно или сделать выборку нужных полей для всех студентов и сверить строки из файла с тем, что есть в выборке. Или сразу в базе запрашивать данные, фильтруя их по данным из файла и если данные не найдены, распечатывать их.

2024-02-12 20:11 UTC, Wladdima commented
Теперь переделал. Надеюсь, получилось правильно. Видимо, я не так понял задание сначала.

2024-02-13 12:07 UTC, eugene-okulik approved these changes
Я двадцать раз переделывал описание и всё равно понимаю, что оно не полностью очевидное. Но у меня закончились попытки )))  
Как ни странно, большинство понимает что я хотел сказать. Меня это даже удивляет. Так что, это ожидаемо, что задание может быть неправильно понято ))

P.S. Удачи со следующим заданием )) Пиши если будут вопросы или будешь видеть, что подвисаешь.

2024-02-13 12:08 UTC, merged