Vladimir Popov Task 24
eugene-okulik/Vladimir_Popov pull request #27
Opened 2024-04-24 20:32 UTC by Wladdima

2024-04-24 20:38 UTC, Wladdima commented
Евгений, привет! 
В файле "test_part1.py" есть один sleep(), чтобы ждать алерт. Не нашел другое решение, к сожалению. 
Еще я пробовал написать локатор для карточки товара через название товара, но не получилось. Имя товара находится в теге a. Посмотри, пожалуйста, почему не находит элемент? 

![locator for tag a](https://github.com/eugene-okulik/Vladimir_Popov/assets/60410078/4f6bbe75-a59f-4358-b89b-5093d7f61936)

2024-04-26 14:49 UTC, eugene-okulik requested changes
Всё хорошо, но со слипом не пропущу )))

2024-04-26 14:49 UTC, eugene-okulik commented on homework/vladimir_popov/Task24/test_part1.py
> +    alert.accept()
Там есть такая штука
```python
EC.alert_is_present()
```

2024-04-29 10:34 UTC, eugene-okulik approved these changes

2024-04-29 10:34 UTC, merged