Vladimir Popov Task 4
eugene-okulik/Vladimir_Popov pull request #4
Opened 2024-01-11 17:55 UTC by Wladdima

2024-01-12 08:09 UTC, eugene-okulik requested changes

2024-01-12 08:09 UTC, eugene-okulik commented on homework/vladimir_popov/Task4/Part1.py
> +country = person[4]
Обращение к элементам списка по индексу - это то, к чему нужно прибегать в крайнем случае, если по-другому никак. Здесь же мы можем использовать распаковку, чем и стоит воспользоваться.

2024-01-12 08:09 UTC, eugene-okulik commented on homework/vladimir_popov/Task4/Part2.py
> +digit_1_index = string_1.split().index("42")
Если мы знаем число еще в момент написания программы, то мы можем сразу написать print(42 + 10)  
Фишка этой программы в том, чтобы она сама нашла число в строке, опираясь на что-то общее для всех строк. Например, количество символов до числа в каждой строке разное, количество символов в числе тоже разное, но есть в структуре этих строк и что-то одинаковое, на что можно опереться.

2024-01-12 18:43 UTC, Wladdima commented on homework/vladimir_popov/Task4/Part2.py
> +digit_1_index = string_1.split().index("42")
Переделал. Когда только начал делать, то сразу возникла идея поделить строку через метод split(":"), так как именно ":" отделяет "число" от строки. Но, перечитав задание еще раз, обратил внимание, что нужно использовать метод index(). Но если честно, я не совсем понимаю где и как его лучше применить, поэтому сделал "тупое" решение через index("число"). Другой способ применить и срезы и индекс я не придумал.

2024-01-14 11:41 UTC, eugene-okulik requested changes

2024-01-14 11:41 UTC, eugene-okulik commented on homework/vladimir_popov/Task4/Part2.py
> +digit_3 = int(string_3.split(":")[1]) + 10
Отлично, но нужно все-таки решить через `index`. С помощью этого `index` мы можем определить где находится это двоеточие - и, исходя из этого знать где в строке начинается число.

2024-01-14 11:41 UTC, eugene-okulik commented on homework/vladimir_popov/Task4/Part1.py
> +name, last_name, city, phone, country = person
👍

2024-01-15 06:53 UTC, eugene-okulik approved these changes
Смотри, чтобы было понятно: я заставлял всё решить через `index` не потому, что так правильнее, а для того, чтобы попрактиковать такой подход. Если брать просто решение задачи, без дополнительных условий, то твое решение через `split` более правильное и аккуратное.

2024-01-15 06:53 UTC, merged

2024-01-15 06:55 UTC, Wladdima commented
Понял, принял, спасибо.